apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  mongo-username: cm9vdA==                # Base64 for 'root'
  mongo-password: ZXhhbXBsZQ==           # Base64 for 'example'
  mongo-uri: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
  redis-password: c29tZXJlZGlzcGFzc3dvcmQ=  # Base64 for 'someredispassword'
